# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use Node.js LTS as the base image
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies including dev dependencies for tsx
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy source code
COPY . .

# Build the package
RUN --mount=type=cache,target=/root/.npm npm run build

# Expose port for HTTP transport
EXPOSE 3005

# Set default environment variables
ENV OPENAPI_MCP_HEADERS="{}"
ENV NODE_ENV="production"

# Set entrypoint to start the server
ENTRYPOINT ["npm", "start"]
